CREATE TABLE Customer (
    CustomerId INT IDENTITY(1,1) PRIMARY KEY,
    FirstName  NVARCHAR(100) NOT NULL,
    LastName   NVARCHAR(100) NOT NULL,
    Email      NVARCHAR(255) NOT NULL,
    CreatedAt  DATETIME NOT NULL DEFAULT GETDATE()
);